// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cartographer/v1/cartographer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_cartographer_v1_cartographer_proto protoreflect.FileDescriptor

const file_cartographer_v1_cartographer_proto_rawDesc = "" +
	"\n" +
	"\"cartographer/v1/cartographer.proto\x12\x0fcartographer.v1\x1a\x1ccartographer/v1/models.proto\x1a\x1ecartographer/v1/requests.proto2\xe2\x03\n" +
	"\fCartographer\x12E\n" +
	"\x04Ping\x12\x1c.cartographer.v1.PingRequest\x1a\x1d.cartographer.v1.PingResponse\"\x00\x12Z\n" +
	"\x03Get\x12'.cartographer.v1.CartographerGetRequest\x1a(.cartographer.v1.CartographerGetResponse\"\x00\x12Z\n" +
	"\x03Add\x12'.cartographer.v1.CartographerAddRequest\x1a(.cartographer.v1.CartographerAddResponse\"\x00\x12c\n" +
	"\x06Delete\x12*.cartographer.v1.CartographerDeleteRequest\x1a+.cartographer.v1.CartographerDeleteResponse\"\x00\x12n\n" +
	"\tStreamGet\x12-.cartographer.v1.CartographerStreamGetRequest\x1a..cartographer.v1.CartographerStreamGetResponse\"\x000\x01B\xb2\x01\n" +
	"\x13com.cartographer.v1B\x11CartographerProtoP\x01Z+github.com/rjbrown57/cartographer/pkg/proto\xa2\x02\x03CXX\xaa\x02\x0fCartographer.V1\xca\x02\x0fCartographer\\V1\xe2\x02\x1bCartographer\\V1\\GPBMetadata\xea\x02\x10Cartographer::V1b\x06proto3"

var file_cartographer_v1_cartographer_proto_goTypes = []any{
	(*PingRequest)(nil),                   // 0: cartographer.v1.PingRequest
	(*CartographerGetRequest)(nil),        // 1: cartographer.v1.CartographerGetRequest
	(*CartographerAddRequest)(nil),        // 2: cartographer.v1.CartographerAddRequest
	(*CartographerDeleteRequest)(nil),     // 3: cartographer.v1.CartographerDeleteRequest
	(*CartographerStreamGetRequest)(nil),  // 4: cartographer.v1.CartographerStreamGetRequest
	(*PingResponse)(nil),                  // 5: cartographer.v1.PingResponse
	(*CartographerGetResponse)(nil),       // 6: cartographer.v1.CartographerGetResponse
	(*CartographerAddResponse)(nil),       // 7: cartographer.v1.CartographerAddResponse
	(*CartographerDeleteResponse)(nil),    // 8: cartographer.v1.CartographerDeleteResponse
	(*CartographerStreamGetResponse)(nil), // 9: cartographer.v1.CartographerStreamGetResponse
}
var file_cartographer_v1_cartographer_proto_depIdxs = []int32{
	0, // 0: cartographer.v1.Cartographer.Ping:input_type -> cartographer.v1.PingRequest
	1, // 1: cartographer.v1.Cartographer.Get:input_type -> cartographer.v1.CartographerGetRequest
	2, // 2: cartographer.v1.Cartographer.Add:input_type -> cartographer.v1.CartographerAddRequest
	3, // 3: cartographer.v1.Cartographer.Delete:input_type -> cartographer.v1.CartographerDeleteRequest
	4, // 4: cartographer.v1.Cartographer.StreamGet:input_type -> cartographer.v1.CartographerStreamGetRequest
	5, // 5: cartographer.v1.Cartographer.Ping:output_type -> cartographer.v1.PingResponse
	6, // 6: cartographer.v1.Cartographer.Get:output_type -> cartographer.v1.CartographerGetResponse
	7, // 7: cartographer.v1.Cartographer.Add:output_type -> cartographer.v1.CartographerAddResponse
	8, // 8: cartographer.v1.Cartographer.Delete:output_type -> cartographer.v1.CartographerDeleteResponse
	9, // 9: cartographer.v1.Cartographer.StreamGet:output_type -> cartographer.v1.CartographerStreamGetResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cartographer_v1_cartographer_proto_init() }
func file_cartographer_v1_cartographer_proto_init() {
	if File_cartographer_v1_cartographer_proto != nil {
		return
	}
	file_cartographer_v1_models_proto_init()
	file_cartographer_v1_requests_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cartographer_v1_cartographer_proto_rawDesc), len(file_cartographer_v1_cartographer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cartographer_v1_cartographer_proto_goTypes,
		DependencyIndexes: file_cartographer_v1_cartographer_proto_depIdxs,
	}.Build()
	File_cartographer_v1_cartographer_proto = out.File
	file_cartographer_v1_cartographer_proto_goTypes = nil
	file_cartographer_v1_cartographer_proto_depIdxs = nil
}
