// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: cartographer/v1/models.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Note represents searchable markdown content with optional URL metadata.
type Note struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"` // need to fix this to use repeated Tag tags
	Data          *structpb.Struct       `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	Id            string                 `protobuf:"bytes,7,opt,name=id,proto3" json:"id,omitempty"`
	Annotations   map[string]string      `protobuf:"bytes,8,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Source        string                 `protobuf:"bytes,11,opt,name=source,proto3" json:"source,omitempty"`
	Author        string                 `protobuf:"bytes,12,opt,name=author,proto3" json:"author,omitempty"`
	Version       int64                  `protobuf:"varint,13,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Note) Reset() {
	*x = Note{}
	mi := &file_cartographer_v1_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Note) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Note) ProtoMessage() {}

func (x *Note) ProtoReflect() protoreflect.Message {
	mi := &file_cartographer_v1_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Note.ProtoReflect.Descriptor instead.
func (*Note) Descriptor() ([]byte, []int) {
	return file_cartographer_v1_models_proto_rawDescGZIP(), []int{0}
}

func (x *Note) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Note) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Note) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Note) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Note) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Note) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Note) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Note) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Note) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Note) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Note) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Note) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// Tag represents a label or category for organizing notes.
type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Annotations   map[string]string      `protobuf:"bytes,3,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_cartographer_v1_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_cartographer_v1_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_cartographer_v1_models_proto_rawDescGZIP(), []int{1}
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tag) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

var File_cartographer_v1_models_proto protoreflect.FileDescriptor

const file_cartographer_v1_models_proto_rawDesc = "" +
	"\n" +
	"\x1ccartographer/v1/models.proto\x12\x0fcartographer.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdd\x03\n" +
	"\x04Note\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12+\n" +
	"\x04data\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x04data\x12\x0e\n" +
	"\x02id\x18\a \x01(\tR\x02id\x12H\n" +
	"\vannotations\x18\b \x03(\v2&.cartographer.v1.Note.AnnotationsEntryR\vannotations\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x16\n" +
	"\x06source\x18\v \x01(\tR\x06source\x12\x16\n" +
	"\x06author\x18\f \x01(\tR\x06author\x12\x18\n" +
	"\aversion\x18\r \x01(\x03R\aversion\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc4\x01\n" +
	"\x03Tag\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12G\n" +
	"\vannotations\x18\x03 \x03(\v2%.cartographer.v1.Tag.AnnotationsEntryR\vannotations\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\xac\x01\n" +
	"\x13com.cartographer.v1B\vModelsProtoP\x01Z+github.com/rjbrown57/cartographer/pkg/proto\xa2\x02\x03CXX\xaa\x02\x0fCartographer.V1\xca\x02\x0fCartographer\\V1\xe2\x02\x1bCartographer\\V1\\GPBMetadata\xea\x02\x10Cartographer::V1b\x06proto3"

var (
	file_cartographer_v1_models_proto_rawDescOnce sync.Once
	file_cartographer_v1_models_proto_rawDescData []byte
)

func file_cartographer_v1_models_proto_rawDescGZIP() []byte {
	file_cartographer_v1_models_proto_rawDescOnce.Do(func() {
		file_cartographer_v1_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cartographer_v1_models_proto_rawDesc), len(file_cartographer_v1_models_proto_rawDesc)))
	})
	return file_cartographer_v1_models_proto_rawDescData
}

var file_cartographer_v1_models_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cartographer_v1_models_proto_goTypes = []any{
	(*Note)(nil),                  // 0: cartographer.v1.Note
	(*Tag)(nil),                   // 1: cartographer.v1.Tag
	nil,                           // 2: cartographer.v1.Note.AnnotationsEntry
	nil,                           // 3: cartographer.v1.Tag.AnnotationsEntry
	(*structpb.Struct)(nil),       // 4: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_cartographer_v1_models_proto_depIdxs = []int32{
	4, // 0: cartographer.v1.Note.data:type_name -> google.protobuf.Struct
	2, // 1: cartographer.v1.Note.annotations:type_name -> cartographer.v1.Note.AnnotationsEntry
	5, // 2: cartographer.v1.Note.created_at:type_name -> google.protobuf.Timestamp
	5, // 3: cartographer.v1.Note.updated_at:type_name -> google.protobuf.Timestamp
	3, // 4: cartographer.v1.Tag.annotations:type_name -> cartographer.v1.Tag.AnnotationsEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_cartographer_v1_models_proto_init() }
func file_cartographer_v1_models_proto_init() {
	if File_cartographer_v1_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cartographer_v1_models_proto_rawDesc), len(file_cartographer_v1_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cartographer_v1_models_proto_goTypes,
		DependencyIndexes: file_cartographer_v1_models_proto_depIdxs,
		MessageInfos:      file_cartographer_v1_models_proto_msgTypes,
	}.Build()
	File_cartographer_v1_models_proto = out.File
	file_cartographer_v1_models_proto_goTypes = nil
	file_cartographer_v1_models_proto_depIdxs = nil
}
