# https://taskfile.dev

version: '3'

tasks:
  installtools:
    desc: "Install tools"
    cmds:
    - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
    - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
    - go install github.com/bufbuild/buf/cmd/buf@latest
    - go install github.com/goreleaser/goreleaser@latest
  buf:
    desc: "Run buf"
    cmds:
    - cd ./proto && buf generate && cd ../
  ts:
    desc: "Run typescript"
    cmds:
    - cd web && npx tsc && cd ../
  build:
    desc: "Build all"
    cmds:
    - task buf
    - task ts
    - task snapshot
  snapshot:
    desc: "Snapshot"
    cmds:
    - goreleaser --snapshot --clean --config ./.goreleaser.yml
  generate:
    desc: "Generate Fake Data and add to cartographer. Can re-run to add more data"
    vars:
      num: 1000
      dataPath: /tmp/data.yaml
    cmds:
    - cartographer generate -c example -n ${num} > ${dataPath}
    - cartographer client add -f ${dataPath}
  serve:
    desc: "start cartographer"
    cmds:
    - cartographer serve -c example
  pprof:
    desc: "start cartographer + Pprof"
    cmds:
    - cartographer serve -c example -pprof
  compose:
    - docker-compose up -d
  build-basic-explorer:
    desc: "build basic explorer"
    cmds:
    - go build -o basic_explorer explorer/basic/main.go
  test-basic-explorer:
    desc: "test basic explorer"
    cmds:
    - task build-basic-explorer
    - task compose
    - ./basic_explorer -url https://restcountries.com/v3.1/name/deutschland
