# https://taskfile.dev

version: '3'

tasks:
  installtools:
    desc: "Install tools"
    cmds:
    - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
    - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
    - go install github.com/bufbuild/buf/cmd/buf@latest
    - go install github.com/goreleaser/goreleaser/v2@latest
    - go install github.com/swaggo/swag/cmd/swag@latest
    - go install github.com/br0xen/boltbrowser@latest
  buf:
    desc: "Run buf"
    cmds:
    - cd ./proto && buf generate && cd ../
  ts:
    desc: "Run typescript"
    cmds:
    - cd web && npx tsc && cd ../
  build:
    desc: "Build all"
    cmds:
    - task: buf
    - task: ts
    - task: swagger
    - task: snapshot
  snapshot:
    desc: "Snapshot"
    cmds:
    - go fmt ./...
    - goreleaser --snapshot --clean --config ./.goreleaser.yml
  generate:
    desc: "Generate Fake Data and add to cartographer. Can re-run to add more data"
    vars:
      num: 5000
      dataPath: /tmp/data.yaml
    cmds:
    - cartographer test generate -n {{.num}} > {{.dataPath}}
    - cartographer client add -f {{.dataPath}}
  serve:
    desc: "start cartographer"
    cmds:
    - cartographer serve -c example
  pprof:
    desc: "start cartographer + Pprof"
    cmds:
    - cartographer serve -c example -pprof
  compose:
    - docker-compose up -d
  build-basic-explorer:
    desc: "build basic explorer"
    cmds:
    - go build -o basic_explorer explorer/basic/main.go
  test-cartographer:
    desc: "run all go tests"
    cmds:
    - go test ./...
  test-basic-explorer:
    desc: "test basic explorer"
    cmds:
    - task build-basic-explorer
    - task compose
    - ./basic_explorer -url https://restcountries.com/v3.1/name/deutschland
  swagger:
    desc: "generate swagger"
    cmds:
    - swag init -g pkg/types/ui/v1.go -d . -o ./pkg/types/ui/docs
  kind:
    desc: "create kind cluster and install cartographer"
    cmds:
    - kind create cluster --name cartographer
    - kind load docker-image ghcr.io/rjbrown57/cartographer:latest --name cartographer
    - helm install cartographer ./charts/cartographer --namespace cartographer --create-namespace
    - kubectl port-forward svc/cartographer 8081:8081 --namespace cartographer
  kindclean:
    desc: "remove kind cluster"
    cmds:
    - kind delete cluster --name cartographer
