apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cartographer.fullname" . }}
data:
{{- range $path, $_ := .Files.Glob "config/*" }}
{{ printf "%s: |-" $path | trimPrefix "config/" | indent 2 }}
{{- $data := $.Files.Get $path }}
{{ tpl $data . | indent 4 }}
{{- end }}


