links: 
  - url: https://github.com/rjbrown57/binman
    displayname: "binman" # A custom display name
    description: "binary manager"
    tags: ["github","tools"]
  - url: https://github.com/rjbrown57/cartographer
    displayname: "cartographer" # A custom display name
    description: "a tool for aggregating and sharing links"
    tags: ["github","tools"]
